use temp
show tables 
desc customer;
--   single insertion of values 
insert into customer  values(8,'cintu','sismapur','m','maharashtra',412112);




-- multiple values insertion without use of colume name  
insert into customer  values(12,'ditou','smapur','A','astraas',652142),
							(9,'chpo','sislapur','F','manipur',323111),
                            (10,'ghota','shilanghat','m','zapampata',121211),
                            (11,'rohi','adharnarg','F','gulabinarg',423211); 
SELECT * FROM  CUSTOMER;

--  id we have only  some colume information thatn  we can add this also 
insert into customer (ID,CNAME) VALUES(13,"ZILPYA"); -- IT GIVE DEFAULT VALUE TO REAST OF THE BOXS \


-- UPDATE

UPDATE CUSTOMER SET ADDRESS ="MIUMBAI",GENDER="M" WHERE ID=13;
-- UPDATE MULTIPLE THINGS AT SAME TIME 
SET SQL_SAFE_UPDATES=0; 
UPDATE CUSTOMER SET PINCODE =110011; -- IT CAN'T ACCESS UNTILE WE  DO THE SQL SAFE UPDATE AS SET IT TO  0 THEN ONLY IT GIVE PERMISSON TO  UPDATE  ALL DATA

-- IF WE WANT TO CHANGE ANY  THING OR VALUE  WE CAN DO THAT ALSO
UPDATE CUSTOMER SET PINCODE = PINCODE+1;
SET SQL_SAFE_UPDATES=1; -- TURN ON  SAFE UPDATE 

-- DELETE COMMAND WORK  
DELETE FROM CUSTOMER WHERE ID =13; 

-- WE CAN DELETE WHOLE TABLE ALSO  BUT IT REQUIRE SAFE MODE OFF
DELETE FROM  CUSTOMER;


-- DELETE CASCADE IT USE TO  HANDLE CONTRENTS OF TABLES
SELECT * FROM ORDER_DETAILS ; 
INSERT INTO  ORDER_DETAILS VALUES(1,"2025-09-20",10);
INSERT INTO ORDER_DETAILS VALUES(2,"2025-08-12",9),(3,"2025-08-09",8);

DELETE FROM CUSTOMER WHERE ID=10; -- SHOW ERROR THAT  I CAN'T DELETE THE  ANY  THING  IN PARENT IF THIRE IS CHILE CONAYINE THE VALUE RELATED TO THAT THING  IN IT
-- FOR THAT WE NEED TO USE ONDELET CASCADE IN  TABLE FROMATION FOR THE  ORDER_DETAILS SO IT WILL SET  THE VALUES ZERO, TO CHNAGE THAT NOW AM CHNAGEING MY  ORDER_DETAIL TABLE DROP PREIVEAS ONE AND CREATE NEW ONE WITH THIS 
 

CREATE TABLE ORDER_DETAILS(
ORDER_ID INTEGER PRIMARY KEY ,
DELIVERY_DATE DATE,
Cust_ID INT,
FOREIGN KEY (Cust_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE
);
-- ------------------------
 
-- REPLACE 
REPLACE	INTO CUSTOMER(ID,CITY) VALUES(11,"PAGLAPUR"); -- IT REMOVE ALL THE EXISTING THINGS FROM THAT ROW  AND REPLACE ONLY GIVEN DATA
REPLACE INTO CUSTOMER(ID,CNAME,CITY)VALUES(15,"SHABLI","RAJAPUR"); -- IT BEHAVE LIKE INSSERT NOW BECOSE THERE IS NO ANY  SUCH ID PRESEN TIN THE TABLE SO  IT ADD THIS TO  END OF THE TABLE  
