   USE TEMP;
   
   
   -- CREATE TABLE ACCOUNT (
--     ID  INT PRIMARY KEY,
--     NAME VARCHAR(255) UNIQUE,
--     BALANCE INT,
--     CONSTRAINT ACC_BLANCE_CHK CHECK(BALANCE>1000)
--     );
    
--     INSERT INTO ACCOUNT (ID,NAME,BALANCE)VALUES(4,'A',113266);
--     INSERT INTO ACCOUNT (ID,NAME,BALANCE)VALUES(3,'B',1056342);
--     SELECT * FROM ACCOUNT ;
    
  -- CREATEING NEW TABLE 
  
	CREATE TABLE NEWACCOUNT(
    ID  INT PRIMARY KEY,
    NAMES VARCHAR(255) UNIQUE,
    BALANCE INT NOT NULL DEFAULT 0 
    );
    
    INSERT INTO NEWACCOUNT (ID,NAME)VALUES(5,'TGB');
    
	SELECT * FROM ACCOUNT2 ;
   
    