create database temp;
use temp;
create table student(id Int PRIMARY KEY,name varchar(255));
INSERT INTO student values(1,'ankit') ;

select * from student;
Drop database IF EXISTS TEMP1;
create database if not exists TEMP2;
Drop database IF EXISTS TEMP2;


-- CREATING CUSTOMER TABLE 
 CREATE TABLE CUSTOMER(
ID integer primary KEY ,
 CNAME VARCHAR(225),
 ADDRESS VARCHAR(225),
 GENDER CHAR(2),
 CITY VARCHAR(225),
PINCODE INTEGER
 );

INSERT INTO CUSTOMER VALUES 
	(1251,'RAM KUMAR','DILBAGH GARDEN','M','PUNE',411100),
    (1252,'SHYAM JADHAV','KOREGAV','M','PUNE',412100),
    (1245,'SIMA HIADER','PAKS','F','PAKISTAN',000000),
    (1287,'CHOTU NUCA','NAPAL','M','NEPAL',878677)
    ;
    
   --  SELECT * FROM CUSTOMER
    
    

CREATE TABLE ORDER_DETAILS(
ORDER_ID INTEGER PRIMARY KEY ,
DELIVERY_DATE DATE,
Cust_ID INT,
FOREIGN KEY (Cust_ID) REFERENCES CUSTOMER(ID)
);

INSERT INTO ORDER_DETAILS VALUES
	(1,'2019-08-12',1245),
    (2,'2020-9-22',1245),
    (3,'2023-3-23',1252),
    (4,'2022-4-28',1287),
    (5,'2024-7-13',1245),
    (6,'2025-5-3',1245),
    (7,'2025-9-11',1252)
    ;
    
   --  SELECT * FROM ORDER_DETAILS
    
    CREATE TABLE ACCOUNT (
    ID  INT PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE,
    BALANCE INT,
    CONSTRAINT ACC_BLANCE_CHK CHECK(BALANCE>1000)
    );
    
    INSERT INTO ACCOUNT(ID,NAME,BALANCE)VALUES(6,'G',10000);
    INSERT INTO ACCOUNT(ID,NAME)VALUES(7,'P'); 
    SELECT * FROM  ACCOUNT;
    
    
    DROP TABLE ACCOUNT;
    
   --  CERATEING THE TABLE WITH DEFAULT VALUE 0 
   CREATE TABLE ACCOUNT (
    ID  INT PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE,
    BALANCE INT NOT NULL DEFAULT 0
    );