-- ALTER OPERTAIONS ON TABLE 
-- WE ALRADY HAD ACCOUNT TABLE WE WANT TO  CHANGE IN THAT SCHEMA 
CREATE TABLE ACCOUNT (
    ID  INT PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE,
    BALANCE INT NOT NULL DEFAULT 0
    );
    
    -- ADD NEW COLUMN
    ALTER TABLE ACCOUNT ADD INTREST FLOAT NOT NULL DEFAULT 0;
    
    -- SUPPOSE I WANT TO MODIFY  THEE INTEREST DATA TYPE FROM FLOAT  TO  DOUBLE
    ALTER TABLE ACCOUNT MODIFY INTREST DOUBLE NOT NULL DEFAULT  0;
    DESC ACCOUNT;
    SELECT  * FROM  ACCOUNT ;
    
    -- CHNAGE COLUMN -USE TO CHNAGE THEE COLUMN NAME 
    ALTER TABLE ACCOUNT CHANGE COLUMN INTREST SAVING_INTREST FLOAT NOT NULL DEFAULT 0;
    
    -- DROP COLUMN IT USE TO DELETE THE PERTICULER COLUMN FROM TABLE SCHEMA
    ALTER TABLE ACCOUNT DROP COLUMN SAVING_INTREST;
    
    
    -- RENAME TO NEW NAME -THE CHNAGE IN TABLE NAME  
    ALTER TABLE ACCOUNT RENAME TO ACCOUNT_DETAILS ;
    DESC ACCOUNT_DETAILS;

