SELECT FIRST_NAME,SALARY FROM WORKER;
USE ORG
SELECT LAST_NAME,JOINING_DATE FROM WORKER ;

SELECT 55+11;
SELECT NOW();
SELECT UCASE('lakhans');
SELECT * FROM WORKER WHERE SALARY >10000 && DEPARTMENT='PM';
SELECT * FROM WORKER WHERE SALARY BETWEEN 200000 AND 976757000;

SELECT * FROM WORKER WHERE DEPARTMENT ='PM' OR DEPARTMENT ='CM';
--  ITS HECTIC WORK TO WRITE ALLWAYS DEPARTMENT INSTED OF THIS WE CAN WRITE IN CLOUSE TO REDUCE THE CODE 

-- SIMPLE CODE TO EXECUT MULTIPLE OR STATMENT AR SINGLE TIME SELECTION WITH OUT WRITING OR   
SELECT * FROM WORKER WHERE DEPARTMENT IN('PM','GHARI','CM');

SELECT * FROM WORKER WHERE DEPARTMENT NOT IN('PM','CM','GHARI');

SELECT * FROM WORKER WHERE DEPARTMENT IS NULL;

-- WILDCARD 
SELECT * FROM WORKER WHERE FIRST_NAME LIKE '%A%';

--  SORTING OF DATA
SELECT * FROM WORKER  ORDER BY SALARY; -- IT IS IN ASE ORDER

-- FOR DECENDING ORDER 
SELECT * FROM WORKER ORDER BY SALARY DESC;
-- WITHOUT DISTECTR FINDER
SELECT  DEPARTMENT FROM WORKER ;
-- WITH DISTINCT DEPARTMENT FINDING 

SELECT DISTINCT DEPARTMENT FROM WORKER ;

-- GROUP BY  WITHOUT AGGREGATION TEAR AS DISTECT VALUES FINDER 
SELECT  DEPARTMENT FROM WORKER GROUP BY  DEPARTMENT ;

-- GROUP BY  WITH  AGGREGATION FUNCTION FIND OPERTIONIN SPECIFIC SET
SELECT DEPARTMENT ,COUNT(DEPARTMENT) FROM WORKER GROUP BY DEPARTMENT;


-- group by avg salary from worker 
SELECT DEPARTMENT ,AVG(SALARY) FROM WORKER GROUP BY DEPARTMENT ;

-- group by max salary from worker
SELECT DEPARTMENT ,max(SALARY) FROM WORKER GROUP BY DEPARTMENT;

-- group by min salary from worker
SELECT DEPARTMENT ,min(SALARY) FROM WORKER GROUP BY DEPARTMENT;

-- group by sum salary from worker
SELECT DEPARTMENT ,SUM(SALARY) FROM WORKER GROUP BY DEPARTMENT;

-- use of having 
SELECT DEPARTMENT, count(DEPARTMENT) FROM WORKER GROUP BY DEPARTMENT HAVING count(DEPARTMENT)>1;

 